export const TELEMETRY_EVENTS = {
  onboardingStart: 'onboarding_start',
  firstInput: 'first_input',
  firstSuccessCoreVerb: 'first_success_core_verb',
  firstFail: 'first_fail',
  retryStart: 'retry_start',
  rewardSeen: 'reward_seen',
  rewardCollected: 'reward_collected',
  rewardUsed: 'reward_used',
  beatCompleted: 'beat_completed',
  secretFound: 'secret_found',
  onboardingComplete: 'onboarding_complete',
  quit: 'quit',
  conceptPlaced: 'concept_placed',
  recallPrompted: 'recall_prompted',
  recallAnswered: 'recall_answered',
  recallTimeout: 'recall_timeout',
  encodePhaseComplete: 'encode_phase_complete',
  recallPhaseComplete: 'recall_phase_complete',
  overworldEntered: 'overworld_entered',
  nodeSelected: 'node_selected',
  sailingStarted: 'sailing_started',
  sightingShown: 'sighting_shown',
  floatingLootCollected: 'floating_loot_collected',
  islandArrived: 'island_arrived',
  islandEncodingComplete: 'island_encoding_complete',
  islandEncounterComplete: 'island_encounter_complete',
  islandComplete: 'island_complete',
  upgradeEarned: 'upgrade_earned',
  scorePromptEarned: 'score_prompt_earned',
  scoreIslandComplete: 'score_island_complete',
  leaderboardViewed: 'leaderboard_viewed',
  leaderboardEntrySubmitted: 'leaderboard_entry_submitted',
  encounterStarted: 'encounter_started',
  encounterPromptAnswered: 'encounter_prompt_answered',
  encounterAssistTriggered: 'encounter_assist_triggered',
  encounterCompleted: 'encounter_completed',
  encounterFailed: 'encounter_failed',
  hudJournalViewed: 'hud_journal_viewed',
  sessionResumed: 'session_resumed',
  offlineQueueDrain: 'offline_queue_drain',
  audioMuted: 'audio_muted',
  clientError: 'client_error',
  stateMachineError: 'state_machine_error',
  assetLoadTimeout: 'asset_load_timeout',
  perfCritical: 'perf_critical',
} as const;

export type TelemetryEventName = (typeof TELEMETRY_EVENTS)[keyof typeof TELEMETRY_EVENTS];

export interface TelemetryEvent {
  eventName: TelemetryEventName;
  payload: Record<string, unknown>;
  ts: string;
}
