/**
 * Cybersecurity DLC Pack
 *
 * Teaches 6 cybersecurity concepts across 2 new islands.
 * Unlocked after completing the base AI/ML campaign (all 5 islands).
 *
 * Topic: Cybersecurity fundamentals — encryption, phishing, firewalls,
 * authentication, malware, and zero-trust.
 */

import type { DlcPack } from '../types';

export const CYBERSECURITY_PACK: DlcPack = {
  manifest: {
    id: 'cybersecurity',
    title: 'Cipher Seas',
    description: 'Navigate encrypted waters and defend against digital pirates!',
    version: '1.0.0',
    topic: 'Cybersecurity',
    conceptCount: 6,
    islandCount: 2,
    prerequisite: 'base_complete',
    tierRange: { min: 1, max: 2 },
  },
  content: {
    islands: [
      {
        id: 'dlc_cipher_cove',
        name: 'Cipher Cove',
        encounterType: 'fog',
        conceptIds: ['encryption', 'phishing', 'firewall'],
        landmarks: [
          { id: 'cipher_lockbox', conceptId: 'encryption', x: 55, y: 285 },
          { id: 'bait_barrel', conceptId: 'phishing', x: 122, y: 218 },
          { id: 'sea_wall', conceptId: 'firewall', x: 186, y: 255 },
        ],
        unlockAfter: 'island_05',
        reward: 'cipher_key_fragment',
        vegetation: ['palm_tree'],
      },
      {
        id: 'dlc_fortress_harbor',
        name: 'Fortress Harbor',
        encounterType: 'battle',
        conceptIds: ['authentication', 'malware', 'zero_trust'],
        landmarks: [
          { id: 'gate_checkpoint', conceptId: 'authentication', x: 52, y: 295 },
          { id: 'cursed_chest', conceptId: 'malware', x: 120, y: 222 },
          { id: 'watchtower', conceptId: 'zero_trust', x: 188, y: 248 },
        ],
        unlockAfter: 'dlc_cipher_cove',
        reward: 'fortress_seal',
        vegetation: ['storm_pine'],
      },
    ],
    concepts: [
      {
        id: 'encryption',
        name: 'Encryption',
        islandId: 'dlc_cipher_cove',
        metaphorObject: 'Cipher Lockbox',
        landmarkId: 'cipher_lockbox',
        tier: 1,
      },
      {
        id: 'phishing',
        name: 'Phishing',
        islandId: 'dlc_cipher_cove',
        metaphorObject: 'Bait Barrel',
        landmarkId: 'bait_barrel',
        tier: 1,
      },
      {
        id: 'firewall',
        name: 'Firewall',
        islandId: 'dlc_cipher_cove',
        metaphorObject: 'Sea Wall',
        landmarkId: 'sea_wall',
        tier: 1,
      },
      {
        id: 'authentication',
        name: 'Authentication',
        islandId: 'dlc_fortress_harbor',
        metaphorObject: 'Gate Checkpoint',
        landmarkId: 'gate_checkpoint',
        tier: 2,
      },
      {
        id: 'malware',
        name: 'Malware',
        islandId: 'dlc_fortress_harbor',
        metaphorObject: 'Cursed Chest',
        landmarkId: 'cursed_chest',
        tier: 2,
      },
      {
        id: 'zero_trust',
        name: 'Zero Trust',
        islandId: 'dlc_fortress_harbor',
        metaphorObject: 'Watchtower',
        landmarkId: 'watchtower',
        tier: 2,
      },
    ],
    encounters: [
      // Reuses fog and battle encounters from base game — no new templates needed.
      // DLCs can add new encounter types if desired.
    ],
    overworldNodes: [
      { islandId: 'dlc_cipher_cove', name: 'Cipher Cove', x: 70, y: 240 },
      { islandId: 'dlc_fortress_harbor', name: 'Fortress Harbor', x: 170, y: 140 },
    ],
    bestiary: [
      {
        id: 'cipher_crab',
        name: 'Cipher Crab',
        category: 'critter',
        flavour: 'A crab whose shell is covered in shifting glyphs.',
        behaviour: 'Patrols near the lockbox. Stuns on contact.',
        danger: 2,
        habitat: ['Cipher Cove'],
        renderHint: 'crab',
      },
      {
        id: 'phish_jelly',
        name: 'Phish Jelly',
        category: 'critter',
        flavour: 'Lures sailors with a false glow, then stings.',
        behaviour: 'Mimics powerup glow. Stuns when approached.',
        danger: 2,
        habitat: ['Cipher Cove', 'Fortress Harbor'],
        renderHint: 'jellyfish',
      },
      {
        id: 'fortress_kelp',
        name: 'Iron Kelp',
        category: 'flora',
        flavour: 'Metallic fronds that clang in the current like alarm bells.',
        behaviour: 'Decorative. Clangs when the wind shifts.',
        danger: 0,
        habitat: ['Fortress Harbor'],
        renderHint: 'glow_kelp',
      },
    ],
    minigames: [
      {
        conceptId: 'encryption',
        conceptName: 'Encryption',
        metaphor: 'Cipher Lockbox',
        dialog: [
          { speaker: 'parrot', text: 'Squawk! This lockbox has a secret code on it!' },
          { speaker: 'parrot', text: 'If ye scramble a message so only the right key opens it, what is that called?' },
          {
            speaker: 'parrot',
            text: 'What say ye?',
            choices: ['Encryption', 'Deletion', 'Copying'],
            correctChoice: 0,
            wrongFeedback: 'Nah — scrambling a message to hide it is encryption!',
            correctFeedback: 'Aye! Encryption scrambles data so only the key holder can read it!',
          },
          { speaker: 'narrator', text: 'Encryption = scrambling information so only authorized readers can decode it.' },
        ],
        challenge: {
          type: 'sort',
          instruction: 'Sort the encrypted messages into the lockbox!',
          items: ['🔒 Encrypted', '📄 Plain', '🔒 Encrypted', '📄 Plain', '🔒 Encrypted'],
          answer: [0, 2, 4],
          successText: 'The lockbox accepts only encrypted messages!',
          hintText: 'Look for the lock symbol — those are encrypted.',
        },
        wrapUp: 'Remember: encryption keeps yer secrets safe on the high seas!',
      },
      {
        conceptId: 'phishing',
        conceptName: 'Phishing',
        metaphor: 'Bait Barrel',
        dialog: [
          { speaker: 'parrot', text: 'Careful! That barrel looks too good to be true!' },
          { speaker: 'parrot', text: 'When someone pretends to be trustworthy to steal yer info, what is that?' },
          {
            speaker: 'parrot',
            text: 'What do ye think?',
            choices: ['Fishing', 'Phishing', 'Wishing'],
            correctChoice: 1,
            wrongFeedback: 'Close! Phishing — with a "ph" — means a fake lure for yer data!',
            correctFeedback: 'Aye! Phishing is a trick to steal yer information!',
          },
          { speaker: 'narrator', text: 'Phishing = a deceptive attempt to steal sensitive information by impersonation.' },
        ],
        challenge: {
          type: 'select',
          instruction: 'Tap the suspicious message! (Which one is phishing?)',
          items: ['Ship log update', 'URGENT: Send gold NOW!', 'Weather report'],
          answer: 1,
          successText: 'Ye spotted the phishing attempt!',
          hintText: 'Phishing uses urgency and fear to trick ye.',
        },
        wrapUp: 'Always be suspicious of messages demanding urgent action, captain!',
      },
      {
        conceptId: 'firewall',
        conceptName: 'Firewall',
        metaphor: 'Sea Wall',
        dialog: [
          { speaker: 'parrot', text: 'See that great wall around the cove? It keeps enemies out!' },
          { speaker: 'parrot', text: 'A digital barrier that filters what comes in and out — what is it called?' },
          {
            speaker: 'parrot',
            text: 'Yer answer?',
            choices: ['A firewall', 'A drawbridge', 'A keyhole'],
            correctChoice: 0,
            wrongFeedback: 'Think of a wall that blocks bad traffic — that be a firewall!',
            correctFeedback: 'Aye! A firewall blocks unauthorized access while letting good traffic through!',
          },
          { speaker: 'narrator', text: 'Firewall = a security system that monitors and controls network traffic.' },
        ],
        challenge: {
          type: 'sort',
          instruction: 'Let friendly ships through the wall, block the pirates!',
          items: ['🚢 Friendly', '🏴‍☠️ Pirate', '🚢 Friendly', '🏴‍☠️ Pirate', '🚢 Friendly'],
          answer: [0, 2, 4],
          successText: 'The sea wall only lets trusted ships through!',
          hintText: 'Block the pirate flags — let friendly ships pass.',
        },
        wrapUp: 'A firewall is yer first line of defense on any network!',
      },
      {
        conceptId: 'authentication',
        conceptName: 'Authentication',
        metaphor: 'Gate Checkpoint',
        dialog: [
          { speaker: 'parrot', text: 'Halt! Who goes there? The gate guard needs proof of identity!' },
          { speaker: 'parrot', text: 'Proving who ye are before getting access — what is that process?' },
          {
            speaker: 'parrot',
            text: 'What say ye?',
            choices: ['Authorization', 'Authentication', 'Automation'],
            correctChoice: 1,
            wrongFeedback: 'Almost! Authentication is proving WHO ye are. Authorization is what ye CAN do.',
            correctFeedback: 'Aye! Authentication verifies yer identity!',
          },
          { speaker: 'narrator', text: 'Authentication = verifying that someone is who they claim to be.' },
        ],
        challenge: {
          type: 'connect',
          instruction: 'Match each sailor to their proof of identity!',
          items: ['Captain', 'First Mate', 'Lookout', 'Seal Ring', 'Compass Badge', 'Spyglass Token'],
          answer: [[0, 3], [1, 4], [2, 5]],
          successText: 'Every sailor proved their identity!',
          hintText: 'Each crew member has a unique token that proves who they are.',
        },
        wrapUp: 'Authentication is the gate that keeps impostors out of yer fortress!',
      },
      {
        conceptId: 'malware',
        conceptName: 'Malware',
        metaphor: 'Cursed Chest',
        dialog: [
          { speaker: 'parrot', text: 'That treasure chest has a dark curse on it! Don\'t open it!' },
          { speaker: 'parrot', text: 'Software designed to harm or exploit a system — what be it called?' },
          {
            speaker: 'parrot',
            text: 'What is it?',
            choices: ['Hardware', 'Malware', 'Software update'],
            correctChoice: 1,
            wrongFeedback: 'Nah — malicious software is called malware!',
            correctFeedback: 'Aye! Malware is malicious software that damages or exploits systems!',
          },
          { speaker: 'narrator', text: 'Malware = malicious software designed to damage, disrupt, or gain unauthorized access.' },
        ],
        challenge: {
          type: 'select',
          instruction: 'Which chest is cursed (contains malware)?',
          items: ['🧰 Tool Chest', '💀 Cursed Chest', '📦 Supply Crate'],
          answer: 1,
          successText: 'Ye avoided the cursed chest!',
          hintText: 'Malware often hides in things that look tempting.',
        },
        wrapUp: 'Never open suspicious chests — or files — without checking for curses first!',
      },
      {
        conceptId: 'zero_trust',
        conceptName: 'Zero Trust',
        metaphor: 'Watchtower',
        dialog: [
          { speaker: 'parrot', text: 'The watchtower checks EVERYONE — even the captain\'s own crew!' },
          { speaker: 'parrot', text: 'A security model that trusts nobody by default — what is it?' },
          {
            speaker: 'parrot',
            text: 'What be it called?',
            choices: ['Full Trust', 'Zero Trust', 'Blind Trust'],
            correctChoice: 1,
            wrongFeedback: 'Nah — the idea is to trust NOBODY by default. Zero Trust!',
            correctFeedback: 'Aye! Zero Trust means verify everything, trust nothing by default!',
          },
          { speaker: 'narrator', text: 'Zero Trust = never trust, always verify — every request is checked regardless of source.' },
        ],
        challenge: {
          type: 'sort',
          instruction: 'Check every visitor at the watchtower — verify all!',
          items: ['✅ Verified', '❓ Unverified', '✅ Verified', '❓ Unverified', '❓ Unverified'],
          answer: [0, 2],
          successText: 'Only verified visitors passed through!',
          hintText: 'In Zero Trust, unverified means denied.',
        },
        wrapUp: 'In Zero Trust, even the captain gets checked at every door!',
      },
    ],
  },
};
